## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [4]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный числом 2.5

In [5]:
np.full(10, 2.5)

array([ 2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5,  2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [7]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [11]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [13]:
np.random.random((3,3,3))

array([[[ 0.43183056,  0.77471333,  0.26941731],
        [ 0.3077246 ,  0.90387503,  0.80358531],
        [ 0.78988774,  0.25207994,  0.75719547]],

       [[ 0.56090081,  0.2955717 ,  0.45953163],
        [ 0.31855024,  0.06500095,  0.34828743],
        [ 0.63068989,  0.41676602,  0.036124  ]],

       [[ 0.34156309,  0.16946661,  0.87246925],
        [ 0.3282893 ,  0.34617897,  0.72452854],
        [ 0.20588337,  0.30476349,  0.81591352]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [14]:
np.random.random(30).mean()

0.51959127281608319

Перемножить матрицы 5x3 и 3x2

In [15]:
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [16]:
np.linspace(0,1,12)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

Заменить максимальный элемент на ноль

In [19]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[ 0.41785177  0.73581719  0.33413474  0.761471    0.46626269  0.83064012
  0.5724957   0.          0.7722154   0.50779928]


Преобразовать массив из float в int

In [23]:
np.arange(10, dtype=np.float32).astype(np.int32, copy=False)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [24]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.37410624  0.77293794  0.8465491   1.00301189  0.46600591
   0.51021246  1.2110849   1.14043553  0.88193431]
 [ 0.37410624  0.          0.75574592  0.82548339  0.8354437   0.09492558
   0.40655546  0.98075217  0.94994036  0.51624292]
 [ 0.77293794  0.75574592  0.          0.07418034  0.38206901  0.75404406
   0.35047905  0.64910764  0.51771743  0.88211082]
 [ 0.8465491   0.82548339  0.07418034  0.          0.36476904  0.82023838
   0.41912458  0.62877993  0.49037357  0.92505501]
 [ 1.00301189  0.8354437   0.38206901  0.36476904  0.          0.78951328
   0.49308215  0.26704044  0.14481154  0.71611338]
 [ 0.46600591  0.09492558  0.75404406  0.82023838  0.78951328  0.
   0.40486017  0.91479167  0.89528096  0.42131848]
 [ 0.51021246  0.40655546  0.35047905  0.41912458  0.49308215  0.40486017
   0.          0.70812358  0.63039606  0.61412375]
 [ 1.2110849   0.98075217  0.64910764  0.62877993  0.26704044  0.91479167
   0.70812358  0.          0.14655923  0.70888868]
 [ 1.140

Случайно расположить p элементов в 2D массив

In [25]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [26]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [27]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


Найти n наибольших значений в массиве

In [28]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9998 9997 9996 9999 9995]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [30]:
import pandas as pd
import numpy as np
food = pd.read_csv('/media/d_2000/data/en.openfoodfacts.org.products.tsv', sep='\t')

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [31]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [32]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [33]:
food.shape[1]

163

Напечатайте все названия столбцов

In [34]:
food.columns

Index([u'code', u'url', u'creator', u'created_t', u'created_datetime',
       u'last_modified_t', u'last_modified_datetime', u'product_name',
       u'generic_name', u'quantity',
       ...
       u'fruits-vegetables-nuts_100g', u'fruits-vegetables-nuts-estimate_100g',
       u'collagen-meat-protein-ratio_100g', u'cocoa_100g', u'chlorophyl_100g',
       u'carbon-footprint_100g', u'nutrition-score-fr_100g',
       u'nutrition-score-uk_100g', u'glycemic-index_100g',
       u'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [35]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [37]:
food.dtypes['-glucose_100g']

dtype('float64')

Как проиндексирован набор данных?

In [38]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [39]:
food.values[18][7]

'Lotus Organic Brown Jasmine Rice'

In [40]:
del food

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [44]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
    
chipo = pd.read_csv(url, sep = '\t')

In [45]:
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [54]:
prices = [float(value[1:]) for value in chipo.item_price]
chipo_new = chipo.copy()
chipo_new.item_price = prices 

chipo10 = chipo_new[chipo_new['item_price'] > 10.00]
print chipo10.head()

len(chipo10)

    order_id  quantity        item_name  \
4          2         2     Chicken Bowl   
5          3         1     Chicken Bowl   
7          4         1    Steak Burrito   
13         7         1     Chicken Bowl   
23        12         1  Chicken Burrito   

                                   choice_description  item_price  
4   [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5   [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
7   [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
13  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25  
23  [[Tomatillo-Green Chili Salsa (Medium), Tomati...       10.98  


1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [59]:
chipo_filtered = chipo_new.sort_values(['item_name','quantity', 'item_price']).drop_duplicates(subset=['item_name','quantity'], keep='last')

chipo_one_prod = chipo_filtered[chipo_filtered.quantity == 1]
price_per_item = chipo_one_prod[['item_name', 'item_price']]
price_per_item.sort_values(by = "item_price", ascending = False)

item_name  item_price
4313                       Steak Salad Bowl       11.89
4239                    Carnitas Salad Bowl       11.89
3546                    Barbacoa Salad Bowl       11.89
3710                       Steak Soft Tacos       11.75
4594                          Barbacoa Bowl       11.75
1632                  Carnitas Crispy Tacos       11.75
4487                       Carnitas Burrito       11.75
4593                          Carnitas Bowl       11.75
4147                    Carnitas Soft Tacos       11.75
4554                     Steak Crispy Tacos       11.75
4618                          Steak Burrito       11.75
4518                             Steak Bowl       11.75
3548                    Barbacoa Soft Tacos       11.75
2787                  Barbacoa Crispy Tacos       11.75
4592                       Barbacoa Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4468                            Veggie Bowl       11.25
4611                         Veggie Burrito       11.25
4502                     Chicken Soft Tacos       11.25
1699                      Veggie Soft Tacos       11.25
4371                   Chicken Crispy Tacos       11.25
4559                        Chicken Burrito       11.25
4590                           Chicken Bowl       11.25
4261                      Veggie Salad Bowl       11.25
1065                          Chicken Salad       10.98
3750                         Carnitas Salad        8.99
893                             Steak Salad        8.99
1653                    Veggie Crispy Tacos        8.49
4084                           Veggie Salad        8.49
521                            Crispy Tacos        7.40
760                                 Burrito        7.40
673                                    Bowl        7.40
1415                                  Salad        7.40
4535                      6 Pack Soft Drink        6.49
4616                    Chips and Guacamole        4.45
3669                                   Izze        3.39
4078                       Nantucket Nectar        3.39
674       Chips and Mild Fresh Tomato Salsa        3.00
4466    Chips and Tomatillo Red Chili Salsa        2.95
4493  Chips and Tomatillo Green Chili Salsa        2.95
3780     Chips and Roasted Chili Corn Salsa        2.95
4503           Chips and Fresh Tomato Salsa        2.95
4088    Chips and Tomatillo-Red Chili Salsa        2.39
4007  Chips and Tomatillo-Green Chili Salsa        2.39
3905     Chips and Roasted Chili-Corn Salsa        2.39
4613                                  Chips        2.15
4070                          Side of Chips        1.69
4614                          Bottled Water        1.50
4609                      Canned Soft Drink        1.25
4051                            Canned Soda        1.09

Отсортировать по имени предмета

In [60]:
chipo.sort_values(by = "item_name")

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [61]:
chipo_new.sort_values(by = "item_price", ascending = False).head(1)

order_id  quantity                     item_name choice_description  \
3598      1443        15  Chips and Fresh Tomato Salsa                NaN   

      item_price  
3598       44.25

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [62]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [63]:
chipo_drink_steak_bowl = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
len(chipo_drink_steak_bowl)

20